Repository Arquisoft/InciManager_i3a, pull requests merged in 2018-04, with the labels that each got.

#59 imporve(login-view): Improved the login view.
  src/main/resources/static/img/inci-manager-logo.png
  src/main/resources/static/signin.css
  src/main/resources/templates/error.html
  src/main/resources/templates/login.html
Labels: PR target: master, affects: web-service, priority: low, status: accepted, type: improvement

#62 [Readme] Update desployment data.
  README.md
Labels: PR target: master, affects: documentation, affects: repository, difficulty: easy-one, priority: medium, status: accepted, type: bug-fix

#61 refactor(code): change pure html to thymeleaf syntax.
  src/main/resources/templates/login.html
Labels: PR target: master, affects: code, affects: web-service, difficulty: easy-one, status: accepted, type: bug-fix

#63 Integrate agents service
  pom.xml
  src/main/java/org/uniovi/i3a/incimanager/Service.java
  src/main/java/org/uniovi/i3a/incimanager/rest/AgentsConnection.java
  src/main/resources/application.properties
  src/test/java/org/uniovi/i3a/incimanager/kafka/KafkaServiceTest.java
  src/test/java/org/uniovi/i3a/incimanager/rest/RESTControllerTest.java
  src/test/java/org/uniovi/i3a/incimanager/web/WebControllerTest.java
Labels: PR target: master, affects: code, affects: rest-service, difficulty: easy-one, priority: low, status: revision needed, type: improvement

#64 Added Dockerfile
  Dockerfile
  pom.xml
Labels: affects: cd, affects: repository, difficulty: easy-one, priority: high, type: bug-fix

#66 Integration with AWS
  pom.xml
  src/main/java/org/uniovi/i3a/incimanager/rest/AgentsConnection.java
  src/main/resources/application.properties
Labels: PR target: master, affects: code, affects: kafka-service, affects: rest-service, affects: web-service, difficulty: easy-one, priority: high, status: accepted, type: bug-fix

#67 Add support for environment variables
  src/main/resources/application.properties
Labels: PR target: master, affects: ci, affects: code, difficulty: easy-one, status: accepted
